name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: edu-self-hosted
    timeout-minutes: 10
    container:
      image: golang:1.23-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.64.8
          output-format: colored-line-number

      - name: Test
        run: |
          go test -v -race -coverpkg=./... ./...
